import type {
  AliasCategory,
  AliasPackage,
  AliasWord,
} from "@/features/alias/types";

type Labels = readonly [en: string, uk: string];

interface CategorySeed {
  id: string;
  label: Labels;
  words: readonly Labels[];
}

interface PackageSeed {
  categories: readonly CategorySeed[];
  id: string;
  label: Labels;
}

interface CuratedCategorySeed {
  excludeWordIds?: readonly string[];
  id: string;
  includeWordIds?: readonly string[];
  label: Labels;
  sourceCategoryId: string;
}

interface CuratedPackageSeed {
  categories: readonly CuratedCategorySeed[];
  id: string;
  label: Labels;
}

function createWords(
  categoryId: string,
  words: readonly Labels[]
): AliasWord[] {
  return words.map(([en, uk], index) => ({
    id: `${categoryId}-${index + 1}`,
    text: { en, uk },
  }));
}

function createCategory(seed: CategorySeed): AliasCategory {
  return {
    id: seed.id,
    label: { en: seed.label[0], uk: seed.label[1] },
    words: createWords(seed.id, seed.words),
  };
}

function createPackage(seed: PackageSeed): AliasPackage {
  return {
    id: seed.id,
    label: { en: seed.label[0], uk: seed.label[1] },
    categories: seed.categories.map(createCategory),
  };
}

function createCuratedCategory(
  seed: CuratedCategorySeed,
  sourceCategoriesById: ReadonlyMap<string, AliasCategory>,
  sourceWordsById: ReadonlyMap<string, AliasWord>
): AliasCategory {
  const sourceCategory = sourceCategoriesById.get(seed.sourceCategoryId);

  if (!sourceCategory) {
    throw new Error(`Unknown Alias source category: ${seed.sourceCategoryId}`);
  }

  const excludedWordIds = new Set(seed.excludeWordIds ?? []);
  const words = sourceCategory.words.filter(
    (word) => !excludedWordIds.has(word.id)
  );

  for (const wordId of seed.includeWordIds ?? []) {
    const word = sourceWordsById.get(wordId);

    if (!word) {
      throw new Error(`Unknown Alias source word: ${wordId}`);
    }

    words.push(word);
  }

  return {
    id: seed.id,
    label: { en: seed.label[0], uk: seed.label[1] },
    words,
  };
}

function createCuratedPackages(
  sourcePackages: readonly AliasPackage[],
  seeds: readonly CuratedPackageSeed[]
): AliasPackage[] {
  const sourceCategories = sourcePackages.flatMap(
    (contentPackage) => contentPackage.categories
  );
  const sourceCategoriesById = new Map(
    sourceCategories.map((category) => [category.id, category])
  );
  const sourceWordsById = new Map(
    sourceCategories.flatMap((category) =>
      category.words.map((word) => [word.id, word] as const)
    )
  );

  return seeds.map((seed) => ({
    id: seed.id,
    label: { en: seed.label[0], uk: seed.label[1] },
    categories: seed.categories.map((categorySeed) =>
      createCuratedCategory(categorySeed, sourceCategoriesById, sourceWordsById)
    ),
  }));
}

const packageSeeds: readonly PackageSeed[] = [
  {
    id: "party",
    label: ["Party", "Вечірка"],
    categories: [
      {
        id: "party-easy",
        label: ["Easy words", "Легкі слова"],
        words: [
          ["Music", "Музика"],
          ["Dance", "Танець"],
          ["Cake", "Торт"],
          ["Balloon", "Кулька"],
          ["Gift", "Подарунок"],
          ["Friend", "Друг"],
          ["Game", "Гра"],
          ["Joke", "Жарт"],
          ["Photo", "Фото"],
          ["Smile", "Усмішка"],
          ["Chair", "Стілець"],
          ["Table", "Стіл"],
          ["Lamp", "Лампа"],
          ["Door", "Двері"],
          ["Window", "Вікно"],
          ["Phone", "Телефон"],
          ["Pizza", "Піца"],
          ["Juice", "Сік"],
          ["Song", "Пісня"],
          ["Movie", "Фільм"],
          ["Clock", "Годинник"],
          ["Shoes", "Взуття"],
          ["Hat", "Капелюх"],
          ["Book", "Книга"],
          ["Key", "Ключ"],
          ["Bag", "Сумка"],
          ["Plate", "Тарілка"],
          ["Cup", "Чашка"],
          ["Spoon", "Ложка"],
          ["Mirror", "Дзеркало"],
          ["Sofa", "Диван"],
          ["Pillow", "Подушка"],
          ["Candy", "Цукерка"],
          ["Flower", "Квітка"],
          ["Star", "Зірка"],
          ["Rain", "Дощ"],
          ["Snow", "Сніг"],
          ["Beach", "Пляж"],
          ["Park", "Парк"],
          ["Taxi", "Таксі"],
        ],
      },
      {
        id: "party-actions",
        label: ["Actions", "Дії"],
        words: [
          ["Run", "Бігти"],
          ["Jump", "Стрибати"],
          ["Whisper", "Шепотіти"],
          ["Laugh", "Сміятися"],
          ["Cook", "Готувати"],
          ["Draw", "Малювати"],
          ["Sing", "Співати"],
          ["Drive", "Керувати"],
          ["Swim", "Плавати"],
          ["Read", "Читати"],
          ["Write", "Писати"],
          ["Listen", "Слухати"],
          ["Build", "Будувати"],
          ["Clean", "Прибирати"],
          ["Hide", "Ховатися"],
          ["Search", "Шукати"],
          ["Open", "Відкривати"],
          ["Close", "Закривати"],
          ["Carry", "Нести"],
          ["Catch", "Ловити"],
          ["Throw", "Кидати"],
          ["Share", "Ділитися"],
          ["Choose", "Обирати"],
          ["Wait", "Чекати"],
          ["Travel", "Подорожувати"],
          ["Paint", "Фарбувати"],
          ["Climb", "Лізти"],
          ["Sleep", "Спати"],
          ["Wake", "Прокидатися"],
          ["Celebrate", "Святкувати"],
          ["Invite", "Запрошувати"],
          ["Explain", "Пояснювати"],
          ["Guess", "Вгадувати"],
          ["Repair", "Ремонтувати"],
          ["Measure", "Вимірювати"],
          ["Count", "Рахувати"],
          ["Borrow", "Позичати"],
          ["Promise", "Обіцяти"],
          ["Remember", "Пам’ятати"],
          ["Forget", "Забувати"],
        ],
      },
    ],
  },
  {
    id: "world",
    label: ["World", "Світ"],
    categories: [
      {
        id: "world-places",
        label: ["Places", "Місця"],
        words: [
          ["Airport", "Аеропорт"],
          ["Hospital", "Лікарня"],
          ["School", "Школа"],
          ["Museum", "Музей"],
          ["Theater", "Театр"],
          ["Market", "Ринок"],
          ["Library", "Бібліотека"],
          ["Stadium", "Стадіон"],
          ["Restaurant", "Ресторан"],
          ["Cafe", "Кафе"],
          ["Bank", "Банк"],
          ["Hotel", "Готель"],
          ["Beach", "Пляж"],
          ["Forest", "Ліс"],
          ["Mountain", "Гора"],
          ["River", "Річка"],
          ["Island", "Острів"],
          ["Desert", "Пустеля"],
          ["Castle", "Замок"],
          ["Factory", "Фабрика"],
          ["Farm", "Ферма"],
          ["Office", "Офіс"],
          ["Cinema", "Кінотеатр"],
          ["Zoo", "Зоопарк"],
          ["Bridge", "Міст"],
          ["Station", "Станція"],
          ["Harbor", "Гавань"],
          ["Garden", "Сад"],
          ["Church", "Церква"],
          ["Square", "Площа"],
          ["Bakery", "Пекарня"],
          ["Pharmacy", "Аптека"],
          ["Salon", "Салон"],
          ["Garage", "Гараж"],
          ["Kitchen", "Кухня"],
          ["Balcony", "Балкон"],
          ["Basement", "Підвал"],
          ["Elevator", "Ліфт"],
          ["Rooftop", "Дах"],
          ["Playground", "Майданчик"],
        ],
      },
      {
        id: "world-nature",
        label: ["Nature", "Природа"],
        words: [
          ["Ocean", "Океан"],
          ["Cloud", "Хмара"],
          ["Thunder", "Грім"],
          ["Lightning", "Блискавка"],
          ["Rainbow", "Веселка"],
          ["Wind", "Вітер"],
          ["Fog", "Туман"],
          ["Volcano", "Вулкан"],
          ["Cave", "Печера"],
          ["Waterfall", "Водоспад"],
          ["Lake", "Озеро"],
          ["Field", "Поле"],
          ["Meadow", "Луг"],
          ["Tree", "Дерево"],
          ["Leaf", "Листок"],
          ["Root", "Корінь"],
          ["Stone", "Камінь"],
          ["Sand", "Пісок"],
          ["Sun", "Сонце"],
          ["Moon", "Місяць"],
          ["Planet", "Планета"],
          ["Comet", "Комета"],
          ["Galaxy", "Галактика"],
          ["Seed", "Насіння"],
          ["Mushroom", "Гриб"],
          ["Berry", "Ягода"],
          ["Apple", "Яблуко"],
          ["Honey", "Мед"],
          ["Fire", "Вогонь"],
          ["Ice", "Лід"],
          ["Storm", "Буря"],
          ["Earthquake", "Землетрус"],
          ["Tide", "Приплив"],
          ["Reef", "Риф"],
          ["Cliff", "Скеля"],
          ["Valley", "Долина"],
          ["Prairie", "Степ"],
          ["Swamp", "Болото"],
          ["Path", "Стежка"],
          ["Horizon", "Горизонт"],
        ],
      },
    ],
  },
  {
    id: "culture",
    label: ["Culture", "Культура"],
    categories: [
      {
        id: "culture-media",
        label: ["Movies and media", "Кіно та медіа"],
        words: [
          ["Actor", "Актор"],
          ["Director", "Режисер"],
          ["Camera", "Камера"],
          ["Script", "Сценарій"],
          ["Trailer", "Трейлер"],
          ["Episode", "Епізод"],
          ["Season", "Сезон"],
          ["Cartoon", "Мультфільм"],
          ["Podcast", "Подкаст"],
          ["News", "Новини"],
          ["Interview", "Інтерв’ю"],
          ["Microphone", "Мікрофон"],
          ["Studio", "Студія"],
          ["Premiere", "Прем’єра"],
          ["Audience", "Аудиторія"],
          ["Hero", "Герой"],
          ["Villain", "Лиходій"],
          ["Plot", "Сюжет"],
          ["Scene", "Сцена"],
          ["Costume", "Костюм"],
          ["Makeup", "Грим"],
          ["Subtitle", "Субтитри"],
          ["Streaming", "Стримінг"],
          ["Channel", "Канал"],
          ["Blogger", "Блогер"],
          ["Comment", "Коментар"],
          ["Like", "Лайк"],
          ["Meme", "Мем"],
          ["Playlist", "Плейлист"],
          ["Concert", "Концерт"],
          ["Album", "Альбом"],
          ["Guitar", "Гітара"],
          ["Piano", "Піаніно"],
          ["Drums", "Барабани"],
          ["Opera", "Опера"],
          ["Ballet", "Балет"],
          ["Festival", "Фестиваль"],
          ["Award", "Нагорода"],
          ["Magazine", "Журнал"],
          ["Poster", "Постер"],
        ],
      },
      {
        id: "culture-ukraine",
        label: ["Ukraine", "Україна"],
        words: [
          ["Kyiv", "Київ"],
          ["Lviv", "Львів"],
          ["Odesa", "Одеса"],
          ["Kharkiv", "Харків"],
          ["Dnipro", "Дніпро"],
          ["Carpathians", "Карпати"],
          ["Dnipro River", "Дніпро"],
          ["Borshch", "Борщ"],
          ["Varenyky", "Вареники"],
          ["Holubtsi", "Голубці"],
          ["Vyshyvanka", "Вишиванка"],
          ["Hryvnia", "Гривня"],
          ["Trembita", "Трембіта"],
          ["Bandura", "Бандура"],
          ["Hopak", "Гопак"],
          ["Cossack", "Козак"],
          ["Pysanka", "Писанка"],
          ["Sunflower", "Соняшник"],
          ["Wheat", "Пшениця"],
          ["Maidan", "Майдан"],
          ["Metro", "Метро"],
          ["Tram", "Трамвай"],
          ["Chestnut", "Каштан"],
          ["Dumka", "Думка"],
          ["Steppe", "Степ"],
          ["Crimea", "Крим"],
          ["Black Sea", "Чорне море"],
          ["Hoverla", "Говерла"],
          ["Sich", "Січ"],
          ["Kobzar", "Кобзар"],
          ["Vertep", "Вертеп"],
          ["Kutia", "Кутя"],
          ["Malanka", "Маланка"],
          ["Embroider", "Вишивати"],
          ["Clay", "Глина"],
          ["Market", "Базар"],
          ["Train", "Потяг"],
          ["Village", "Село"],
          ["City", "Місто"],
          ["Independence", "Незалежність"],
        ],
      },
    ],
  },
  {
    id: "lifestyle",
    label: ["Lifestyle", "Стиль життя"],
    categories: [
      {
        id: "lifestyle-food",
        label: ["Food and drinks", "Їжа та напої"],
        words: [
          ["Breakfast", "Сніданок"],
          ["Dinner", "Вечеря"],
          ["Soup", "Суп"],
          ["Salad", "Салат"],
          ["Sandwich", "Сендвіч"],
          ["Burger", "Бургер"],
          ["Pasta", "Паста"],
          ["Rice", "Рис"],
          ["Cheese", "Сир"],
          ["Butter", "Масло"],
          ["Bread", "Хліб"],
          ["Croissant", "Круасан"],
          ["Pancake", "Млинець"],
          ["Waffle", "Вафля"],
          ["Chocolate", "Шоколад"],
          ["Ice cream", "Морозиво"],
          ["Cookie", "Печиво"],
          ["Donut", "Пончик"],
          ["Water", "Вода"],
          ["Tea", "Чай"],
          ["Coffee", "Кава"],
          ["Lemonade", "Лимонад"],
          ["Milkshake", "Молочний коктейль"],
          ["Smoothie", "Смузі"],
          ["Orange", "Апельсин"],
          ["Banana", "Банан"],
          ["Grapes", "Виноград"],
          ["Watermelon", "Кавун"],
          ["Carrot", "Морква"],
          ["Potato", "Картопля"],
          ["Tomato", "Помідор"],
          ["Cucumber", "Огірок"],
          ["Pepper", "Перець"],
          ["Garlic", "Часник"],
          ["Salt", "Сіль"],
          ["Sugar", "Цукор"],
          ["Honey", "Мед"],
          ["Jam", "Варення"],
          ["Menu", "Меню"],
          ["Recipe", "Рецепт"],
        ],
      },
      {
        id: "lifestyle-home",
        label: ["Home and routine", "Дім і побут"],
        words: [
          ["Bedroom", "Спальня"],
          ["Bathroom", "Ванна"],
          ["Hallway", "Коридор"],
          ["Closet", "Шафа"],
          ["Blanket", "Ковдра"],
          ["Towel", "Рушник"],
          ["Soap", "Мило"],
          ["Toothbrush", "Зубна щітка"],
          ["Shampoo", "Шампунь"],
          ["Laundry", "Прання"],
          ["Vacuum", "Пилосос"],
          ["Broom", "Мітла"],
          ["Bucket", "Відро"],
          ["Trash", "Сміття"],
          ["Remote", "Пульт"],
          ["Charger", "Зарядка"],
          ["Outlet", "Розетка"],
          ["Calendar", "Календар"],
          ["Notebook", "Блокнот"],
          ["Pen", "Ручка"],
          ["Wallet", "Гаманець"],
          ["Umbrella", "Парасолька"],
          ["Jacket", "Куртка"],
          ["Scarf", "Шарф"],
          ["Gloves", "Рукавички"],
          ["Laundry basket", "Кошик для білизни"],
          ["Doorbell", "Дзвінок"],
          ["Mailbox", "Поштова скринька"],
          ["Curtain", "Штора"],
          ["Carpet", "Килим"],
          ["Shelf", "Полиця"],
          ["Drawer", "Шухляда"],
          ["Fridge", "Холодильник"],
          ["Oven", "Духовка"],
          ["Kettle", "Чайник"],
          ["Microwave", "Мікрохвильовка"],
          ["Dishwasher", "Посудомийка"],
          ["Iron", "Праска"],
          ["Alarm clock", "Будильник"],
          ["Houseplant", "Кімнатна рослина"],
        ],
      },
    ],
  },
  {
    id: "modern",
    label: ["Modern life", "Сучасне життя"],
    categories: [
      {
        id: "modern-tech",
        label: ["Tech", "Технології"],
        words: [
          ["Laptop", "Ноутбук"],
          ["Tablet", "Планшет"],
          ["Keyboard", "Клавіатура"],
          ["Mouse", "Мишка"],
          ["Monitor", "Монітор"],
          ["Headphones", "Навушники"],
          ["Speaker", "Динамік"],
          ["Router", "Роутер"],
          ["Password", "Пароль"],
          ["Login", "Вхід"],
          ["Website", "Сайт"],
          ["Browser", "Браузер"],
          ["Application", "Застосунок"],
          ["Notification", "Сповіщення"],
          ["Battery", "Батарея"],
          ["Cable", "Кабель"],
          ["Cloud", "Хмара"],
          ["Download", "Завантаження"],
          ["Upload", "Вивантаження"],
          ["Emoji", "Емодзі"],
          ["Message", "Повідомлення"],
          ["Video call", "Відеодзвінок"],
          ["Selfie", "Селфі"],
          ["Filter", "Фільтр"],
          ["Profile", "Профіль"],
          ["Username", "Ім’я користувача"],
          ["Search engine", "Пошуковик"],
          ["Map", "Мапа"],
          ["Navigation", "Навігація"],
          ["Robot", "Робот"],
          ["Drone", "Дрон"],
          ["Printer", "Принтер"],
          ["Scanner", "Сканер"],
          ["Flash drive", "Флешка"],
          ["Update", "Оновлення"],
          ["Bug", "Помилка"],
          ["Code", "Код"],
          ["Algorithm", "Алгоритм"],
          ["Database", "База даних"],
          ["Firewall", "Фаєрвол"],
        ],
      },
      {
        id: "modern-work",
        label: ["Work and jobs", "Робота і професії"],
        words: [
          ["Engineer", "Інженер"],
          ["Designer", "Дизайнер"],
          ["Teacher", "Вчитель"],
          ["Doctor", "Лікар"],
          ["Nurse", "Медсестра"],
          ["Lawyer", "Юрист"],
          ["Accountant", "Бухгалтер"],
          ["Manager", "Менеджер"],
          ["Assistant", "Асистент"],
          ["Courier", "Кур’єр"],
          ["Driver", "Водій"],
          ["Chef", "Шеф-кухар"],
          ["Waiter", "Офіціант"],
          ["Cashier", "Касир"],
          ["Seller", "Продавець"],
          ["Photographer", "Фотограф"],
          ["Journalist", "Журналіст"],
          ["Translator", "Перекладач"],
          ["Programmer", "Програміст"],
          ["Analyst", "Аналітик"],
          ["Architect", "Архітектор"],
          ["Builder", "Будівельник"],
          ["Electrician", "Електрик"],
          ["Plumber", "Сантехнік"],
          ["Mechanic", "Механік"],
          ["Farmer", "Фермер"],
          ["Pilot", "Пілот"],
          ["Scientist", "Науковець"],
          ["Veterinarian", "Ветеринар"],
          ["Dentist", "Стоматолог"],
          ["Barber", "Барбер"],
          ["Florist", "Флорист"],
          ["Guard", "Охоронець"],
          ["Firefighter", "Пожежник"],
          ["Police officer", "Поліцейський"],
          ["Soldier", "Військовий"],
          ["Coach", "Тренер"],
          ["Artist", "Художник"],
          ["Musician", "Музикант"],
          ["Entrepreneur", "Підприємець"],
        ],
      },
    ],
  },
  {
    id: "active",
    label: ["Active", "Активність"],
    categories: [
      {
        id: "active-sports",
        label: ["Sports and hobbies", "Спорт і хобі"],
        words: [
          ["Football", "Футбол"],
          ["Basketball", "Баскетбол"],
          ["Volleyball", "Волейбол"],
          ["Tennis", "Теніс"],
          ["Boxing", "Бокс"],
          ["Yoga", "Йога"],
          ["Running", "Біг"],
          ["Cycling", "Велоспорт"],
          ["Skiing", "Лижі"],
          ["Skating", "Ковзани"],
          ["Surfing", "Серфінг"],
          ["Fishing", "Риболовля"],
          ["Camping", "Кемпінг"],
          ["Hiking", "Похід"],
          ["Chess", "Шахи"],
          ["Puzzle", "Пазл"],
          ["Board game", "Настільна гра"],
          ["Darts", "Дартс"],
          ["Bowling", "Боулінг"],
          ["Billiards", "Більярд"],
          ["Gardening", "Садівництво"],
          ["Knitting", "В’язання"],
          ["Photography", "Фотографія"],
          ["Origami", "Орігамі"],
          ["Pottery", "Гончарство"],
          ["Calligraphy", "Каліграфія"],
          ["Collecting", "Колекціонування"],
          ["Karaoke", "Караоке"],
          ["Dancing", "Танці"],
          ["Acting", "Акторство"],
          ["Magic trick", "Фокус"],
          ["Marathon", "Марафон"],
          ["Medal", "Медаль"],
          ["Tournament", "Турнір"],
          ["Teamwork", "Командна робота"],
          ["Warm-up", "Розминка"],
          ["Training", "Тренування"],
          ["Goalkeeper", "Воротар"],
          ["Referee", "Суддя"],
          ["Champion", "Чемпіон"],
        ],
      },
    ],
  },
  {
    id: "challenge",
    label: ["Challenge", "Виклик"],
    categories: [
      {
        id: "challenge-feelings",
        label: ["Feelings and personality", "Почуття та характер"],
        words: [
          ["Happy", "Щасливий"],
          ["Sad", "Сумний"],
          ["Angry", "Злий"],
          ["Calm", "Спокійний"],
          ["Nervous", "Нервовий"],
          ["Brave", "Сміливий"],
          ["Shy", "Сором’язливий"],
          ["Curious", "Допитливий"],
          ["Lazy", "Лінивий"],
          ["Honest", "Чесний"],
          ["Patient", "Терплячий"],
          ["Jealous", "Ревнивий"],
          ["Proud", "Гордий"],
          ["Guilty", "Винний"],
          ["Confused", "Розгублений"],
          ["Excited", "Збуджений"],
          ["Bored", "Нудьгуючий"],
          ["Lonely", "Самотній"],
          ["Grateful", "Вдячний"],
          ["Hopeful", "Сповнений надії"],
          ["Stubborn", "Впертий"],
          ["Generous", "Щедрий"],
          ["Greedy", "Жадібний"],
          ["Polite", "Ввічливий"],
          ["Rude", "Грубий"],
          ["Creative", "Креативний"],
          ["Serious", "Серйозний"],
          ["Silly", "Дурненький"],
          ["Confident", "Впевнений"],
          ["Careful", "Обережний"],
          ["Careless", "Необережний"],
          ["Kind", "Добрий"],
          ["Cruel", "Жорстокий"],
          ["Funny", "Смішний"],
          ["Moody", "Мінливий"],
          ["Optimistic", "Оптимістичний"],
          ["Pessimistic", "Песимістичний"],
          ["Sensitive", "Чутливий"],
          ["Ambitious", "Амбітний"],
          ["Humble", "Скромний"],
          ["Arrogant", "Зарозумілий"],
          ["Relaxed", "Розслаблений"],
          ["Anxious", "Тривожний"],
          ["Surprised", "Здивований"],
          ["Disappointed", "Розчарований"],
          ["Inspired", "Натхненний"],
          ["Embarrassed", "Збентежений"],
          ["Determined", "Рішучий"],
          ["Friendly", "Дружній"],
          ["Suspicious", "Підозрілий"],
          ["Loyal", "Вірний"],
          ["Independent", "Незалежний"],
          ["Responsible", "Відповідальний"],
          ["Impulsive", "Імпульсивний"],
          ["Awkward", "Незграбний"],
          ["Charming", "Чарівний"],
          ["Thoughtful", "Уважний"],
        ],
      },
      {
        id: "challenge-animals",
        label: ["Animals", "Тварини"],
        words: [
          ["Dog", "Собака"],
          ["Cat", "Кіт"],
          ["Horse", "Кінь"],
          ["Cow", "Корова"],
          ["Pig", "Свиня"],
          ["Sheep", "Вівця"],
          ["Goat", "Коза"],
          ["Chicken", "Курка"],
          ["Duck", "Качка"],
          ["Goose", "Гуска"],
          ["Turkey", "Індик"],
          ["Rabbit", "Кролик"],
          ["Hamster", "Хом’як"],
          ["Mouse", "Миша"],
          ["Rat", "Пацюк"],
          ["Squirrel", "Білка"],
          ["Fox", "Лисиця"],
          ["Wolf", "Вовк"],
          ["Bear", "Ведмідь"],
          ["Deer", "Олень"],
          ["Moose", "Лось"],
          ["Lion", "Лев"],
          ["Tiger", "Тигр"],
          ["Leopard", "Леопард"],
          ["Cheetah", "Гепард"],
          ["Elephant", "Слон"],
          ["Giraffe", "Жирафа"],
          ["Zebra", "Зебра"],
          ["Rhino", "Носоріг"],
          ["Hippo", "Бегемот"],
          ["Monkey", "Мавпа"],
          ["Gorilla", "Горила"],
          ["Chimpanzee", "Шимпанзе"],
          ["Kangaroo", "Кенгуру"],
          ["Koala", "Коала"],
          ["Panda", "Панда"],
          ["Camel", "Верблюд"],
          ["Llama", "Лама"],
          ["Donkey", "Осел"],
          ["Hedgehog", "Їжак"],
          ["Bat", "Кажан"],
          ["Dolphin", "Дельфін"],
          ["Whale", "Кит"],
          ["Shark", "Акула"],
          ["Octopus", "Восьминіг"],
          ["Crab", "Краб"],
          ["Lobster", "Омар"],
          ["Turtle", "Черепаха"],
          ["Frog", "Жаба"],
          ["Snake", "Змія"],
          ["Lizard", "Ящірка"],
          ["Crocodile", "Крокодил"],
          ["Penguin", "Пінгвін"],
          ["Eagle", "Орел"],
          ["Owl", "Сова"],
          ["Parrot", "Папуга"],
          ["Flamingo", "Фламінго"],
          ["Swan", "Лебідь"],
          ["Peacock", "Павич"],
          ["Crow", "Ворона"],
          ["Pigeon", "Голуб"],
          ["Sparrow", "Горобець"],
          ["Bee", "Бджола"],
          ["Butterfly", "Метелик"],
          ["Ant", "Мураха"],
          ["Spider", "Павук"],
          ["Scorpion", "Скорпіон"],
          ["Beetle", "Жук"],
          ["Mosquito", "Комар"],
          ["Grasshopper", "Коник"],
          ["Snail", "Равлик"],
          ["Worm", "Черв’як"],
          ["Jellyfish", "Медуза"],
          ["Seahorse", "Морський коник"],
          ["Starfish", "Морська зірка"],
          ["Seal", "Тюлень"],
          ["Walrus", "Морж"],
          ["Otter", "Видра"],
          ["Raccoon", "Єнот"],
          ["Skunk", "Скунс"],
          ["Beaver", "Бобер"],
          ["Badger", "Борсук"],
          ["Lynx", "Рись"],
          ["Bison", "Бізон"],
          ["Yak", "Як"],
          ["Reindeer", "Північний олень"],
          ["Ostrich", "Страус"],
          ["Pelican", "Пелікан"],
          ["Mantis", "Богомол"],
        ],
      },
      {
        id: "challenge-travel",
        label: ["Travel", "Подорожі"],
        words: [
          ["Passport", "Паспорт"],
          ["Visa", "Віза"],
          ["Ticket", "Квиток"],
          ["Boarding pass", "Посадковий талон"],
          ["Suitcase", "Валіза"],
          ["Backpack", "Рюкзак"],
          ["Luggage", "Багаж"],
          ["Map", "Карта"],
          ["Compass", "Компас"],
          ["Guidebook", "Путівник"],
          ["Reservation", "Бронювання"],
          ["Reception", "Ресепшн"],
          ["Hostel", "Хостел"],
          ["Motel", "Мотель"],
          ["Resort", "Курорт"],
          ["Tent", "Намет"],
          ["Campfire", "Вогнище"],
          ["Sleeping bag", "Спальний мішок"],
          ["Hiking boots", "Туристичні черевики"],
          ["Sunscreen", "Сонцезахисний крем"],
          ["Sunglasses", "Сонцезахисні окуляри"],
          ["Souvenir", "Сувенір"],
          ["Postcard", "Листівка"],
          ["Tourist", "Турист"],
          ["Guide", "Гід"],
          ["Excursion", "Екскурсія"],
          ["Itinerary", "Маршрут"],
          ["Destination", "Напрямок"],
          ["Departure", "Відправлення"],
          ["Arrival", "Прибуття"],
          ["Delay", "Затримка"],
          ["Gate", "Вихід на посадку"],
          ["Terminal", "Термінал"],
          ["Customs", "Митниця"],
          ["Border", "Кордон"],
          ["Currency", "Валюта"],
          ["Exchange office", "Обмінник"],
          ["Receipt", "Чек"],
          ["Taxi stand", "Стоянка таксі"],
          ["Rental car", "Орендоване авто"],
          ["Scooter", "Самокат"],
          ["Ferry", "Пором"],
          ["Cruise", "Круїз"],
          ["Cabin", "Каюта"],
          ["Platform", "Платформа"],
          ["Timetable", "Розклад"],
          ["Railway", "Залізниця"],
          ["Highway", "Шосе"],
          ["Tunnel", "Тунель"],
          ["Checkpoint", "Блокпост"],
          ["Roundabout", "Кільцева розв’язка"],
          ["Parking", "Паркування"],
          ["Fuel station", "Заправка"],
          ["Rest stop", "Зона відпочинку"],
          ["Picnic", "Пікнік"],
          ["Trail", "Маршрут"],
          ["Viewpoint", "Оглядовий майданчик"],
          ["Landmark", "Пам’ятка"],
          ["Monument", "Пам’ятник"],
          ["Old town", "Старе місто"],
          ["Cathedral", "Собор"],
          ["Palace", "Палац"],
          ["Fortress", "Фортеця"],
          ["Ruins", "Руїни"],
          ["Aquarium", "Акваріум"],
          ["Botanical garden", "Ботанічний сад"],
          ["Theme park", "Парк розваг"],
          ["Water park", "Аквапарк"],
          ["Ski lift", "Підйомник"],
          ["Cable car", "Канатна дорога"],
          ["Host family", "Приймаюча родина"],
          ["Translator", "Перекладач"],
          ["Local food", "Місцева їжа"],
          ["Street market", "Вуличний ринок"],
          ["Flea market", "Блошиний ринок"],
          ["Bargain", "Вигідна покупка"],
          ["Queue", "Черга"],
          ["Travel insurance", "Туристичне страхування"],
          ["First aid kit", "Аптечка"],
          ["Emergency", "Надзвичайна ситуація"],
          ["Lost luggage", "Втрачений багаж"],
          ["Travel pillow", "Дорожня подушка"],
          ["Earplugs", "Беруші"],
          ["Power bank", "Павербанк"],
          ["Adapter", "Перехідник"],
          ["Roaming", "Роумінг"],
          ["Wi-Fi password", "Пароль Wi-Fi"],
          ["Travel blog", "Тревел-блог"],
          ["Photo album", "Фотоальбом"],
          ["Drone shot", "Зйомка дроном"],
          ["Sunrise", "Схід сонця"],
          ["Sunset", "Захід сонця"],
          ["Jet lag", "Зміна часових поясів"],
          ["Time zone", "Часовий пояс"],
          ["One-way trip", "Подорож в один бік"],
          ["Round trip", "Подорож туди й назад"],
          ["Weekend getaway", "Поїздка на вихідні"],
          ["Business trip", "Відрядження"],
          ["Road trip", "Автомандрівка"],
          ["Honeymoon trip", "Весільна подорож"],
          ["Family vacation", "Сімейна відпустка"],
          ["City break", "Коротка міська подорож"],
          ["Backpacking", "Подорож з рюкзаком"],
          ["Island hopping", "Подорож островами"],
          ["Safari", "Сафарі"],
          ["Expedition", "Експедиція"],
          ["Pilgrimage", "Паломництво"],
          ["Detour", "Об’їзд"],
          ["Shortcut", "Короткий шлях"],
          ["Scenic route", "Мальовничий маршрут"],
          ["Travel companion", "Супутник у подорожі"],
          ["Local legend", "Місцева легенда"],
          ["Hidden gem", "Прихована перлина"],
          ["Tour bus", "Туристичний автобус"],
          ["Double room", "Двомісний номер"],
          ["Room service", "Обслуговування номерів"],
          ["Check-in", "Реєстрація"],
          ["Check-out", "Виселення"],
          ["All-inclusive", "Все включено"],
          ["Travel budget", "Бюджет подорожі"],
        ],
      },
      {
        id: "challenge-science",
        label: ["Science", "Наука"],
        words: [
          ["Atom", "Атом"],
          ["Molecule", "Молекула"],
          ["Electron", "Електрон"],
          ["Proton", "Протон"],
          ["Neutron", "Нейтрон"],
          ["Gravity", "Гравітація"],
          ["Energy", "Енергія"],
          ["Force", "Сила"],
          ["Motion", "Рух"],
          ["Friction", "Тертя"],
          ["Pressure", "Тиск"],
          ["Temperature", "Температура"],
          ["Experiment", "Експеримент"],
          ["Hypothesis", "Гіпотеза"],
          ["Theory", "Теорія"],
          ["Formula", "Формула"],
          ["Laboratory", "Лабораторія"],
          ["Microscope", "Мікроскоп"],
          ["Telescope", "Телескоп"],
          ["Beaker", "Склянка"],
          ["Test tube", "Пробірка"],
          ["Magnet", "Магніт"],
          ["Circuit", "Схема"],
          ["Battery", "Батарея"],
          ["Current", "Струм"],
          ["Voltage", "Напруга"],
          ["Spectrum", "Спектр"],
          ["Laser", "Лазер"],
          ["Radiation", "Випромінювання"],
          ["Sound wave", "Звукова хвиля"],
          ["Light year", "Світловий рік"],
          ["Orbit", "Орбіта"],
          ["Satellite", "Супутник"],
          ["Asteroid", "Астероїд"],
          ["Black hole", "Чорна діра"],
          ["Nebula", "Туманність"],
          ["Gravity well", "Гравітаційна яма"],
          ["Rocket", "Ракета"],
          ["Spacesuit", "Скафандр"],
          ["Space station", "Космічна станція"],
          ["DNA", "ДНК"],
          ["Gene", "Ген"],
          ["Cell", "Клітина"],
          ["Virus", "Вірус"],
          ["Bacteria", "Бактерія"],
          ["Protein", "Білок"],
          ["Organ", "Орган"],
          ["Skeleton", "Скелет"],
          ["Muscle", "М’яз"],
          ["Nerve", "Нерв"],
          ["Brain", "Мозок"],
          ["Heart", "Серце"],
          ["Lung", "Легеня"],
          ["Blood", "Кров"],
          ["Oxygen", "Кисень"],
          ["Carbon", "Вуглець"],
          ["Hydrogen", "Водень"],
          ["Nitrogen", "Азот"],
          ["Metal", "Метал"],
          ["Crystal", "Кристал"],
          ["Acid", "Кислота"],
          ["Base", "Основа"],
          ["Reaction", "Реакція"],
          ["Catalyst", "Каталізатор"],
          ["Solution", "Розчин"],
          ["Mixture", "Суміш"],
          ["Evaporation", "Випаровування"],
          ["Condensation", "Конденсація"],
          ["Freezing", "Замерзання"],
          ["Melting", "Плавлення"],
          ["Erosion", "Ерозія"],
          ["Fossil", "Скам’янілість"],
          ["Evolution", "Еволюція"],
          ["Ecosystem", "Екосистема"],
          ["Habitat", "Середовище існування"],
          ["Climate", "Клімат"],
          ["Weather", "Погода"],
          ["Atmosphere", "Атмосфера"],
          ["Magnetic field", "Магнітне поле"],
          ["Tectonic plate", "Тектонічна плита"],
          ["Volcanic ash", "Вулканічний попіл"],
          ["Seismograph", "Сейсмограф"],
          ["Probability", "Ймовірність"],
          ["Statistics", "Статистика"],
          ["Graph", "Графік"],
          ["Equation", "Рівняння"],
          ["Variable", "Змінна"],
          ["Measurement", "Вимірювання"],
          ["Accuracy", "Точність"],
          ["Discovery", "Відкриття"],
          ["Innovation", "Інновація"],
          ["Research", "Дослідження"],
          ["Data", "Дані"],
          ["Observation", "Спостереження"],
        ],
      },
      {
        id: "challenge-objects",
        label: ["Everyday objects", "Повсякденні речі"],
        words: [
          ["Needle", "Голка"],
          ["Thread", "Нитка"],
          ["Button", "Ґудзик"],
          ["Zipper", "Блискавка"],
          ["Belt", "Ремінь"],
          ["Shoelace", "Шнурок"],
          ["Hanger", "Вішак"],
          ["Basket", "Кошик"],
          ["Box", "Коробка"],
          ["Envelope", "Конверт"],
          ["Stamp", "Марка"],
          ["Tape", "Скотч"],
          ["Glue", "Клей"],
          ["Scissors", "Ножиці"],
          ["Ruler", "Лінійка"],
          ["Marker", "Маркер"],
          ["Crayon", "Олівець"],
          ["Eraser", "Гумка"],
          ["Stapler", "Степлер"],
          ["Paperclip", "Скріпка"],
          ["Folder", "Папка"],
          ["Binder", "Швидкозшивач"],
          ["Backpack", "Рюкзак"],
          ["Lunchbox", "Ланчбокс"],
          ["Thermos", "Термос"],
          ["Bottle opener", "Відкривачка"],
          ["Corkscrew", "Штопор"],
          ["Can opener", "Консервний ніж"],
          ["Frying pan", "Пательня"],
          ["Saucepan", "Каструля"],
          ["Ladle", "Ополоник"],
          ["Whisk", "Вінчик"],
          ["Cutting board", "Дошка для нарізання"],
          ["Grater", "Терка"],
          ["Strainer", "Друшляк"],
          ["Apron", "Фартух"],
          ["Napkin", "Серветка"],
          ["Coaster", "Підставка"],
          ["Tray", "Таця"],
          ["Vase", "Ваза"],
          ["Frame", "Рамка"],
          ["Candle", "Свічка"],
          ["Matchbox", "Коробка сірників"],
          ["Flashlight", "Ліхтарик"],
          ["Lantern", "Ліхтар"],
          ["Battery pack", "Акумулятор"],
          ["Extension cord", "Подовжувач"],
          ["Adapter plug", "Перехідник"],
          ["Switch", "Вимикач"],
          ["Thermostat", "Термостат"],
          ["Fan", "Вентилятор"],
          ["Heater", "Обігрівач"],
          ["Air conditioner", "Кондиціонер"],
          ["Humidifier", "Зволожувач"],
          ["Door handle", "Дверна ручка"],
          ["Lock", "Замок"],
          ["Keychain", "Брелок"],
          ["Padlock", "Навісний замок"],
          ["Toolbox", "Ящик для інструментів"],
          ["Hammer", "Молоток"],
          ["Screwdriver", "Викрутка"],
          ["Wrench", "Гайковий ключ"],
          ["Pliers", "Плоскогубці"],
          ["Drill", "Дриль"],
          ["Nail", "Цвях"],
          ["Screw", "Гвинт"],
          ["Hook", "Гачок"],
          ["Rope", "Мотузка"],
          ["Chain", "Ланцюг"],
          ["Ladder", "Драбина"],
          ["Brush", "Щітка"],
          ["Sponge", "Губка"],
          ["Detergent", "Мийний засіб"],
          ["Mop", "Швабра"],
          ["Dustpan", "Совок"],
          ["Trash bag", "Пакет для сміття"],
          ["Bin", "Смітник"],
          ["Doormat", "Килимок біля дверей"],
          ["Purse", "Гаманець"],
          ["Briefcase", "Портфель"],
          ["Suitcase tag", "Бірка на валізу"],
          ["Watch", "Годинник"],
          ["Bracelet", "Браслет"],
          ["Necklace", "Намисто"],
          ["Ring", "Перстень"],
          ["Comb", "Гребінець"],
          ["Hairbrush", "Щітка для волосся"],
          ["Razor", "Бритва"],
          ["Nail file", "Пилка для нігтів"],
          ["Lip balm", "Бальзам для губ"],
          ["Perfume", "Парфуми"],
          ["Medicine", "Ліки"],
          ["Bandage", "Бинт"],
          ["Thermometer", "Термометр"],
          ["Umbrella stand", "Підставка для парасольок"],
          ["Shopping cart", "Візок"],
          ["Price tag", "Цінник"],
          ["Receipt printer", "Принтер чеків"],
          ["Name tag", "Бейдж"],
          ["Clipboard", "Планшет із затискачем"],
          ["Megaphone", "Мегафон"],
          ["Bell", "Дзвінок"],
          ["Whistle", "Свисток"],
          ["Helmet", "Шолом"],
          ["Knee pad", "Наколінник"],
          ["Life jacket", "Рятувальний жилет"],
          ["Back scratcher", "Чухалка для спини"],
          ["Magnifying glass", "Лупа"],
          ["Binoculars", "Бінокль"],
          ["Tripod", "Штатив"],
          ["Memory card", "Карта пам’яті"],
          ["Remote control", "Пульт керування"],
          ["Game controller", "Ігровий контролер"],
          ["Microfiber cloth", "Мікрофібра"],
          ["Storage jar", "Банка для зберігання"],
          ["Ice tray", "Форма для льоду"],
          ["Measuring cup", "Мірна чашка"],
          ["Kitchen timer", "Кухонний таймер"],
          ["Shoehorn", "Ложка для взуття"],
          ["Doorstop", "Обмежувач дверей"],
        ],
      },
    ],
  },
  {
    id: "social",
    label: ["Social", "Спілкування"],
    categories: [
      {
        id: "social-party",
        label: ["Party stories", "Вечірні історії"],
        words: [
          ["Cocktail", "Коктейль"],
          ["Mocktail", "Безалкогольний коктейль"],
          ["Flirt", "Флірт"],
          ["Date", "Побачення"],
          ["Kiss", "Поцілунок"],
          ["Jealousy", "Ревнощі"],
          ["Secret crush", "Таємна симпатія"],
          ["Ex", "Колишній"],
          ["Awkward silence", "Незручна тиша"],
          ["Red flag", "Червоний прапорець"],
          ["Bachelor party", "Парубоцька вечірка"],
          ["Bachelorette party", "Дівич-вечір"],
          ["Nightclub", "Нічний клуб"],
          ["Bartender", "Бармен"],
          ["Toast", "Тост"],
          ["Truth", "Правда"],
          ["Dare", "Дія"],
          ["Gossip", "Плітки"],
          ["Romance", "Романтика"],
          ["Breakup", "Розрив"],
          ["Blind date", "Побачення наосліп"],
          ["Pickup line", "Фраза для знайомства"],
          ["Private joke", "Особистий жарт"],
          ["Afterparty", "Афтерпаті"],
          ["Karaoke bar", "Караоке-бар"],
          ["Champagne", "Шампанське"],
          ["Confession", "Зізнання"],
          ["Roommate drama", "Драма з сусідом"],
          ["Slow dance", "Повільний танець"],
          ["Love triangle", "Любовний трикутник"],
          ["Party rumor", "Вечірня чутка"],
          ["Secret message", "Таємне повідомлення"],
          ["Morning after", "Ранок після вечірки"],
          ["Bad decision", "Погане рішення"],
          ["Dress code", "Дрескод"],
          ["Guest list", "Список гостей"],
          ["Name card", "Іменна картка"],
          ["Welcome drink", "Вітальний напій"],
          ["Table plan", "План столів"],
          ["Group photo", "Групове фото"],
          ["Dance floor", "Танцмайданчик"],
          ["DJ booth", "Пульт діджея"],
          ["Party playlist", "Плейлист вечірки"],
          ["Photo booth", "Фотобудка"],
          ["Funny toast", "Смішний тост"],
          ["Inside joke", "Жарт для своїх"],
          ["Lost jacket", "Загублена куртка"],
          ["Wrong room", "Не та кімната"],
          ["Surprise guest", "Неочікуваний гість"],
          ["Late arrival", "Запізнення"],
          ["Early exit", "Ранній вихід"],
          ["Shared taxi", "Спільне таксі"],
          ["Party host", "Господар вечірки"],
          ["Invitation", "Запрошення"],
          ["Polaroid", "Полароїд"],
          ["Glitter", "Блискітки"],
          ["Paper crown", "Паперова корона"],
          ["Confetti cannon", "Хлопавка з конфеті"],
          ["Snack table", "Стіл із закусками"],
          ["Coat check", "Гардероб"],
        ],
      },
      {
        id: "social-relationships",
        label: ["Relationships", "Стосунки"],
        words: [
          ["First date", "Перше побачення"],
          ["Secret admirer", "Таємний шанувальник"],
          ["Chemistry", "Хімія"],
          ["Attraction", "Потяг"],
          ["Anniversary", "Річниця"],
          ["Engagement", "Заручини"],
          ["Proposal", "Освідчення"],
          ["Honeymoon", "Медовий місяць"],
          ["Couple", "Пара"],
          ["Commitment", "Зобов’язання"],
          ["Mixed signals", "Незрозумілі сигнали"],
          ["Jealous partner", "Ревнивий партнер"],
          ["Romantic dinner", "Романтична вечеря"],
          ["Candlelight", "Свічки"],
          ["Love letter", "Любовний лист"],
          ["Midnight text", "Нічне повідомлення"],
          ["Secret meeting", "Таємна зустріч"],
          ["Dating app", "Застосунок для знайомств"],
          ["Match", "Збіг"],
          ["Ghosting", "Ігнорування"],
          ["Crush", "Симпатія"],
          ["Heartbreak", "Розбите серце"],
          ["Rebound", "Нові стосунки після розриву"],
          ["Flirty smile", "Кокетлива усмішка"],
          ["Compliment", "Комплімент"],
          ["Personal boundary", "Особиста межа"],
          ["Trust", "Довіра"],
          ["Awkward date", "Незручне побачення"],
          ["Romantic surprise", "Романтичний сюрприз"],
          ["Couples therapy", "Парна терапія"],
          ["Relationship drama", "Драма у стосунках"],
          ["Forbidden crush", "Заборонена симпатія"],
          ["Shared secret", "Спільна таємниця"],
          ["Long distance", "Стосунки на відстані"],
          ["Soulmate", "Споріднена душа"],
          ["Friendship", "Дружба"],
          ["Apology", "Вибачення"],
          ["Forgiveness", "Прощення"],
          ["Bouquet", "Букет"],
          ["Walk in park", "Прогулянка в парку"],
          ["Movie night", "Кіновечір"],
          ["Couple selfie", "Селфі пари"],
          ["Family dinner", "Сімейна вечеря"],
          ["Meet parents", "Знайомство з батьками"],
          ["First impression", "Перше враження"],
          ["Promise ring", "Каблучка-обіцянка"],
          ["Shared playlist", "Спільний плейлист"],
          ["Calendar reminder", "Нагадування в календарі"],
          ["Coffee date", "Побачення за кавою"],
          ["Love song", "Пісня про кохання"],
          ["Holding hands", "Триматися за руки"],
          ["Picnic date", "Пікнік-побачення"],
          ["Surprise call", "Неочікуваний дзвінок"],
          ["Goodnight message", "Повідомлення на добраніч"],
          ["Wedding dance", "Весільний танець"],
          ["Seating plan", "План розсадки"],
          ["Photo album", "Фотоальбом"],
          ["Couple costume", "Парний костюм"],
          ["Mutual friend", "Спільний друг"],
          ["Second chance", "Другий шанс"],
        ],
      },
    ],
  },
  {
    id: "mixed",
    label: ["Mixed", "Мікс"],
    categories: [
      {
        id: "mixed-city",
        label: ["City details", "Міські деталі"],
        words: [
          ["Crosswalk", "Пішохідний перехід"],
          ["Streetlight", "Ліхтар"],
          ["Bus stop", "Зупинка автобуса"],
          ["Tram line", "Трамвайна лінія"],
          ["Ticket booth", "Каса"],
          ["Newsstand", "Кіоск із пресою"],
          ["Flower stall", "Квітковий кіоск"],
          ["Food truck", "Фудтрак"],
          ["Bike lane", "Велодоріжка"],
          ["Traffic cone", "Дорожній конус"],
          ["Parking meter", "Паркомат"],
          ["City map", "Карта міста"],
          ["Public fountain", "Міський фонтан"],
          ["Bench plaque", "Табличка на лавці"],
          ["Street musician", "Вуличний музикант"],
          ["Tour guide", "Екскурсовод"],
          ["Souvenir shop", "Сувенірна крамниця"],
          ["Clock tower", "Годинникова вежа"],
          ["City hall", "Міська рада"],
          ["Post office", "Пошта"],
          ["Fire station", "Пожежна частина"],
          ["Police booth", "Поліцейський пункт"],
          ["Metro token", "Жетон метро"],
          ["Escalator", "Ескалатор"],
          ["Turnstile", "Турнікет"],
          ["Platform sign", "Вказівник платформи"],
          ["Lost office", "Бюро знахідок"],
          ["Street market", "Вуличний ринок"],
          ["Courier bag", "Сумка кур’єра"],
          ["Delivery scooter", "Скутер доставки"],
          ["Window display", "Вітрина"],
          ["Shop awning", "Маркіза магазину"],
          ["Laundry sign", "Вивіска пральні"],
          ["Barbershop pole", "Стовпчик барбершопу"],
          ["Graffiti wall", "Стіна з графіті"],
          ["Mural", "Мурал"],
          ["Pavement crack", "Тріщина в бруківці"],
          ["Manhole cover", "Кришка люка"],
          ["Rain gutter", "Водостік"],
          ["Busker hat", "Капелюх музиканта"],
          ["Taxi meter", "Лічильник таксі"],
          ["Hotel lobby", "Лобі готелю"],
          ["Reception desk", "Стійка рецепції"],
          ["Luggage cart", "Візок для багажу"],
          ["Doorman", "Швейцар"],
          ["Elevator music", "Музика в ліфті"],
          ["Rooftop view", "Краєвид з даху"],
          ["City skyline", "Панорама міста"],
          ["Construction crane", "Будівельний кран"],
          ["Safety vest", "Сигнальний жилет"],
          ["Road sign", "Дорожній знак"],
          ["One-way street", "Одностороння вулиця"],
          ["Roundabout", "Кільцева розв’язка"],
          ["Pedestrian zone", "Пішохідна зона"],
          ["Canal bridge", "Міст через канал"],
          ["Ferry stop", "Зупинка порома"],
          ["Observation deck", "Оглядовий майданчик"],
          ["City festival", "Міський фестиваль"],
          ["Night bus", "Нічний автобус"],
          ["Quiet courtyard", "Тихий дворик"],
          ["Apartment buzzer", "Домофон"],
          ["Balcony plants", "Рослини на балконі"],
          ["Neighborhood chat", "Чат сусідів"],
          ["Street parade", "Вуличний парад"],
          ["Pop-up shop", "Тимчасова крамниця"],
          ["Community board", "Дошка оголошень"],
          ["Recycling bin", "Контейнер для сортування"],
          ["Water hydrant", "Пожежний гідрант"],
          ["City pigeon", "Міський голуб"],
          ["Morning commute", "Ранкова дорога"],
        ],
      },
      {
        id: "mixed-events",
        label: ["Events", "Події"],
        words: [
          ["Opening ceremony", "Церемонія відкриття"],
          ["Award speech", "Промова нагородження"],
          ["Standing ovation", "Овація стоячи"],
          ["Ticket scanner", "Сканер квитків"],
          ["Wristband", "Браслет учасника"],
          ["Stage lights", "Сценічне світло"],
          ["Sound check", "Саундчек"],
          ["Backstage pass", "Перепустка за куліси"],
          ["Program booklet", "Програма заходу"],
          ["Name badge", "Бейдж з іменем"],
          ["Conference hall", "Конференц-зала"],
          ["Coffee break", "Кава-брейк"],
          ["Panel talk", "Панельна дискусія"],
          ["Workshop", "Воркшоп"],
          ["Networking", "Нетворкінг"],
          ["Keynote", "Головна доповідь"],
          ["Slide deck", "Презентація"],
          ["Microphone stand", "Стійка мікрофона"],
          ["Question card", "Картка з питанням"],
          ["Photo wall", "Фотозона"],
          ["Sponsor banner", "Банер спонсора"],
          ["Volunteer", "Волонтер"],
          ["Registration desk", "Стійка реєстрації"],
          ["Queue rope", "Обмежувальна стрічка"],
          ["VIP area", "VIP-зона"],
          ["Merch table", "Стіл із мерчем"],
          ["Food court", "Фудкорт"],
          ["Festival map", "Карта фестивалю"],
          ["Main stage", "Головна сцена"],
          ["Side stage", "Мала сцена"],
          ["Encore", "Виступ на біс"],
          ["Audience chant", "Скандування глядачів"],
          ["Light show", "Світлове шоу"],
          ["Smoke machine", "Дим-машина"],
          ["Costume contest", "Конкурс костюмів"],
          ["Charity auction", "Благодійний аукціон"],
          ["Raffle ticket", "Лотерейний квиток"],
          ["Prize draw", "Розіграш призів"],
          ["Closing party", "Заключна вечірка"],
          ["Aftermovie", "Відео після події"],
          ["Live stream", "Пряма трансляція"],
          ["Press badge", "Пресбейдж"],
          ["Interview corner", "Куточок інтерв’ю"],
          ["Security check", "Перевірка безпеки"],
          ["Lost bracelet", "Загублений браслет"],
          ["Rain delay", "Затримка через дощ"],
          ["Emergency exit", "Аварійний вихід"],
          ["First aid tent", "Пункт першої допомоги"],
          ["Information desk", "Інфостійка"],
          ["Meetup point", "Місце зустрічі"],
          ["Group ticket", "Груповий квиток"],
          ["Seat number", "Номер місця"],
          ["Balcony seat", "Місце на балконі"],
          ["Standing area", "Фан-зона"],
          ["Dress rehearsal", "Генеральна репетиція"],
          ["Talent show", "Шоу талантів"],
          ["Team contest", "Командний конкурс"],
          ["Trivia round", "Раунд вікторини"],
          ["Lucky winner", "Щасливий переможець"],
          ["Thank-you note", "Подяка"],
          ["Event recap", "Підсумок події"],
          ["Feedback form", "Форма відгуку"],
          ["Guest speaker", "Запрошений спікер"],
          ["Silent auction", "Тихий аукціон"],
          ["Launch party", "Вечірка запуску"],
          ["Open mic", "Відкритий мікрофон"],
          ["Dance battle", "Танцювальний батл"],
          ["Board game night", "Вечір настільних ігор"],
          ["Potluck dinner", "Спільна вечеря"],
          ["Team photo", "Командне фото"],
        ],
      },
      {
        id: "mixed-learning",
        label: ["Learning", "Навчання"],
        words: [
          ["Notebook margin", "Поле в зошиті"],
          ["Highlighter", "Маркер"],
          ["Flashcard", "Картка для навчання"],
          ["Quiz question", "Питання тесту"],
          ["Answer sheet", "Бланк відповідей"],
          ["Study group", "Навчальна група"],
          ["Class monitor", "Староста"],
          ["Whiteboard marker", "Маркер для дошки"],
          ["Chalk dust", "Крейдяний пил"],
          ["Lesson plan", "План уроку"],
          ["Homework folder", "Папка з домашнім"],
          ["Reading list", "Список читання"],
          ["Book report", "Відгук на книгу"],
          ["Science fair", "Науковий ярмарок"],
          ["Lab coat", "Лабораторний халат"],
          ["Test tube", "Пробірка"],
          ["Microscope slide", "Скельце мікроскопа"],
          ["Math formula", "Математична формула"],
          ["Geometry set", "Набір для геометрії"],
          ["Compass needle", "Голка циркуля"],
          ["Graph paper", "Міліметровий папір"],
          ["History timeline", "Історична шкала"],
          ["Language app", "Застосунок для мов"],
          ["Pronunciation", "Вимова"],
          ["Vocabulary list", "Словниковий список"],
          ["Grammar rule", "Граматичне правило"],
          ["Essay draft", "Чернетка есе"],
          ["Peer review", "Взаємна перевірка"],
          ["Presentation clicker", "Клікер для презентацій"],
          ["Project partner", "Партнер у проєкті"],
          ["Group grade", "Групова оцінка"],
          ["Pop quiz", "Раптовий тест"],
          ["Final exam", "Підсумковий іспит"],
          ["Cheat sheet", "Шпаргалка"],
          ["Study break", "Перерва в навчанні"],
          ["Library card", "Читацький квиток"],
          ["Quiet room", "Тиха кімната"],
          ["Tutor", "Репетитор"],
          ["Online course", "Онлайн-курс"],
          ["Video lesson", "Відеоурок"],
          ["Practice task", "Практичне завдання"],
          ["Course badge", "Бейдж курсу"],
          ["Certificate", "Сертифікат"],
          ["Skill tree", "Дерево навичок"],
          ["Progress bar", "Індикатор прогресу"],
          ["Deadline", "Дедлайн"],
          ["Late submission", "Пізня здача"],
          ["Rubric", "Критерії оцінювання"],
          ["Feedback note", "Коментар викладача"],
          ["Office hours", "Години консультацій"],
          ["Study playlist", "Плейлист для навчання"],
          ["Desk lamp", "Настільна лампа"],
          ["Sticky note", "Стікери"],
          ["Index card", "Картка"],
          ["Mind map", "Ментальна мапа"],
          ["Brainstorm", "Мозковий штурм"],
          ["Case study", "Кейс"],
          ["Role play", "Рольова гра"],
          ["Debate topic", "Тема дебатів"],
          ["Practice exam", "Тренувальний іспит"],
          ["Revision notes", "Конспект повторення"],
          ["Study timer", "Таймер навчання"],
          ["Bookmark tab", "Закладка"],
          ["Course forum", "Форум курсу"],
          ["Class chat", "Чат класу"],
          ["Teacher’s pet", "Улюбленець учителя"],
          ["School bell", "Шкільний дзвінок"],
          ["Report card", "Табель"],
          ["Field trip", "Екскурсія"],
          ["Graduation cap", "Випускна шапочка"],
        ],
      },
    ],
  },
];

const sourceAliasPackages = packageSeeds.map(createPackage);

const curatedPackageSeeds: readonly CuratedPackageSeed[] = [
  {
    id: "party",
    label: ["Quick play", "Швидка гра"],
    categories: [
      {
        id: "party-easy",
        sourceCategoryId: "party-easy",
        label: ["Starter words", "Стартові слова"],
        excludeWordIds: [
          "party-easy-17",
          "party-easy-18",
          "party-easy-33",
          "party-easy-34",
          "party-easy-36",
          "party-easy-37",
          "party-easy-38",
          "party-easy-39",
          "party-easy-40",
        ],
      },
      {
        id: "party-actions",
        sourceCategoryId: "party-actions",
        label: ["Actions and verbs", "Дії та дієслова"],
      },
    ],
  },
  {
    id: "world",
    label: ["Places and nature", "Місця та природа"],
    categories: [
      {
        id: "world-places",
        sourceCategoryId: "world-places",
        label: ["Places and buildings", "Місця та будівлі"],
        includeWordIds: ["party-easy-38", "party-easy-39", "party-easy-40"],
      },
      {
        id: "world-nature",
        sourceCategoryId: "world-nature",
        label: ["Nature and weather", "Природа та погода"],
        excludeWordIds: ["world-nature-27", "world-nature-28"],
        includeWordIds: ["party-easy-34", "party-easy-36", "party-easy-37"],
      },
    ],
  },
  {
    id: "culture",
    label: ["Culture and Ukraine", "Культура та Україна"],
    categories: [
      {
        id: "culture-media",
        sourceCategoryId: "culture-media",
        label: ["Movies, music and media", "Кіно, музика та медіа"],
      },
      {
        id: "culture-ukraine",
        sourceCategoryId: "culture-ukraine",
        label: ["Ukraine", "Україна"],
      },
    ],
  },
  {
    id: "lifestyle",
    label: ["Food, home and things", "Їжа, дім і речі"],
    categories: [
      {
        id: "lifestyle-food",
        sourceCategoryId: "lifestyle-food",
        label: ["Food and drinks", "Їжа та напої"],
        includeWordIds: [
          "party-easy-17",
          "party-easy-18",
          "party-easy-33",
          "world-nature-27",
          "world-nature-28",
        ],
      },
      {
        id: "lifestyle-home",
        sourceCategoryId: "lifestyle-home",
        label: ["Home and routine", "Дім і побут"],
      },
      {
        id: "challenge-objects",
        sourceCategoryId: "challenge-objects",
        label: ["Everyday tools and objects", "Побутові речі та інструменти"],
      },
    ],
  },
  {
    id: "modern",
    label: ["Work, tech and learning", "Робота, технології та навчання"],
    categories: [
      {
        id: "modern-tech",
        sourceCategoryId: "modern-tech",
        label: ["Tech and digital life", "Технології та цифрове життя"],
        excludeWordIds: ["modern-tech-28", "modern-tech-29"],
        includeWordIds: ["mixed-learning-23"],
      },
      {
        id: "modern-work",
        sourceCategoryId: "modern-work",
        label: ["Work and professions", "Робота та професії"],
      },
      {
        id: "mixed-learning",
        sourceCategoryId: "mixed-learning",
        label: ["School and learning", "Школа та навчання"],
        excludeWordIds: [
          "mixed-learning-14",
          "mixed-learning-15",
          "mixed-learning-16",
          "mixed-learning-17",
          "mixed-learning-18",
          "mixed-learning-23",
          "mixed-learning-69",
        ],
      },
    ],
  },
  {
    id: "active",
    label: ["Sports and animals", "Спорт і тварини"],
    categories: [
      {
        id: "active-sports",
        sourceCategoryId: "active-sports",
        label: ["Sports and hobbies", "Спорт і хобі"],
      },
      {
        id: "challenge-animals",
        sourceCategoryId: "challenge-animals",
        label: ["Animals", "Тварини"],
      },
    ],
  },
  {
    id: "challenge",
    label: ["Brain stretch", "Складніші слова"],
    categories: [
      {
        id: "challenge-feelings",
        sourceCategoryId: "challenge-feelings",
        label: ["Feelings and personality", "Почуття та характер"],
      },
      {
        id: "challenge-science",
        sourceCategoryId: "challenge-science",
        label: ["Science and discovery", "Наука та відкриття"],
        includeWordIds: [
          "mixed-learning-14",
          "mixed-learning-15",
          "mixed-learning-16",
          "mixed-learning-17",
          "mixed-learning-18",
        ],
      },
    ],
  },
  {
    id: "social",
    label: ["Social and events", "Спілкування та події"],
    categories: [
      {
        id: "social-party",
        sourceCategoryId: "social-party",
        label: ["Party stories", "Вечірні історії"],
        excludeWordIds: [
          "social-party-37",
          "social-party-39",
          "social-party-40",
          "social-party-41",
          "social-party-42",
          "social-party-43",
          "social-party-44",
        ],
        includeWordIds: ["mixed-events-68", "mixed-events-69"],
      },
      {
        id: "social-relationships",
        sourceCategoryId: "social-relationships",
        label: ["Relationships", "Стосунки"],
      },
      {
        id: "mixed-events",
        sourceCategoryId: "mixed-events",
        label: ["Events and venues", "Події та майданчики"],
        excludeWordIds: ["mixed-events-68", "mixed-events-69"],
        includeWordIds: [
          "social-party-37",
          "social-party-39",
          "social-party-40",
          "social-party-41",
          "social-party-42",
          "social-party-43",
          "social-party-44",
        ],
      },
    ],
  },
  {
    id: "mixed",
    label: ["City and travel", "Місто та подорожі"],
    categories: [
      {
        id: "mixed-city",
        sourceCategoryId: "mixed-city",
        label: ["City details", "Міські деталі"],
      },
      {
        id: "challenge-travel",
        sourceCategoryId: "challenge-travel",
        label: ["Travel and transport", "Подорожі та транспорт"],
        includeWordIds: [
          "modern-tech-28",
          "modern-tech-29",
          "mixed-learning-69",
        ],
      },
    ],
  },
];

export const aliasPackages = createCuratedPackages(
  sourceAliasPackages,
  curatedPackageSeeds
);

export const aliasCategoryIds = aliasPackages.flatMap((contentPackage) =>
  contentPackage.categories.map((category) => category.id)
);

export function getAliasCategoryById(categoryId: string) {
  return aliasPackages
    .flatMap((contentPackage) => contentPackage.categories)
    .find((category) => category.id === categoryId);
}

export function getAliasWordById(wordId: string) {
  return aliasPackages
    .flatMap((contentPackage) => contentPackage.categories)
    .flatMap((category) => category.words)
    .find((word) => word.id === wordId);
}

function getAliasWordKey(word: AliasWord) {
  return `${word.text.en.trim().toLowerCase()}|${word.text.uk.trim().toLowerCase()}`;
}

export function getAliasWordIdsForCategories(categoryIds: readonly string[]) {
  const selectedCategoryIds = new Set(categoryIds);
  const seenWordKeys = new Set<string>();
  const wordIds: string[] = [];

  for (const word of aliasPackages
    .flatMap((contentPackage) => contentPackage.categories)
    .filter((category) => selectedCategoryIds.has(category.id))
    .flatMap((category) => category.words)) {
    const wordKey = getAliasWordKey(word);

    if (!seenWordKeys.has(wordKey)) {
      seenWordKeys.add(wordKey);
      wordIds.push(word.id);
    }
  }

  return wordIds;
}

export function getAliasWordCount() {
  return aliasPackages.reduce(
    (total, contentPackage) =>
      total +
      contentPackage.categories.reduce(
        (categoryTotal, category) => categoryTotal + category.words.length,
        0
      ),
    0
  );
}
